/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FeedbackManagementGUI.GUI;

/**
 *
 * @author Berkay
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        changePanel("LoginRegisterSelection");
    }

        /**
     * Changes the current panel by removing all objects from frame and recreate them.
     * @param panelName panel name to get replaced into frame.
     */
    public void changePanel(String panelName)
    {
        if (panelName.equalsIgnoreCase("LoginRegisterSelection"))
        {
            getContentPane().removeAll();
            getContentPane().add(new LoginRegisterSelectionPanel(this));
            pack();
            repaint();
            setSize(300, 300);
        } 
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FeedBackManagementApp");
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
