/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FeedbackManagement.GUI;

import FeedbackManagement.MainApplication;
import FeedbackManagement.RepositoryStatistics;
import FeedbackManagement.Tables.FeedbackTablePanel;
import FeedbackManagement.Tables.ResponseTablePanel;
import FeedbackManagement.Tables.UserTablePanel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
    
/**
 *
 * @author Serhat Korkmaz
 */
public class AdminPanel extends javax.swing.JPanel {
    private final MainFrame mainFrame;
    private javax.swing.JPanel tablePanel;

    /**
     * Creates new customizer AdminPanel
     */
    public AdminPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }
    
    public void ChangePanel(String s){
        TablePanel.removeAll();
        switch (s) {
            case "User":
                tablePanel = new UserTablePanel();
                break;
            case "Feedback":
                tablePanel = new FeedbackTablePanel();
                break;
            case "Response":
                tablePanel = new ResponseTablePanel();
                break;
            case "Statistics":
                tablePanel = new StatisticsPanel();
                break;
            default:
                break;
        }
        TablePanel.add(tablePanel);
        TablePanel.validate();
        TablePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePanel = new javax.swing.JPanel();
        UserButton = new javax.swing.JButton();
        FeedbacksButton = new javax.swing.JButton();
        ResponsesButton = new javax.swing.JButton();
        StatisticsButton = new javax.swing.JButton();
        deleteOldButton = new javax.swing.JButton();
        updateOldButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        UserButton.setText("Users");
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });

        FeedbacksButton.setText("Feedbacks");
        FeedbacksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbacksButtonActionPerformed(evt);
            }
        });

        ResponsesButton.setText("Responses");
        ResponsesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponsesButtonActionPerformed(evt);
            }
        });

        StatisticsButton.setText("Statistics");
        StatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsButtonActionPerformed(evt);
            }
        });

        deleteOldButton.setText("Delete Old Records");
        deleteOldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOldButtonActionPerformed(evt);
            }
        });

        updateOldButton.setText("Update Old Records");
        updateOldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOldButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FeedbacksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ResponsesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StatisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteOldButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateOldButton))
                            .addComponent(logoutButton))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserButton)
                    .addComponent(FeedbacksButton)
                    .addComponent(ResponsesButton)
                    .addComponent(StatisticsButton)
                    .addComponent(deleteOldButton)
                    .addComponent(updateOldButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FeedbacksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbacksButtonActionPerformed
        ChangePanel("Feedback");
    }//GEN-LAST:event_FeedbacksButtonActionPerformed

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed
       ChangePanel("User");
    }//GEN-LAST:event_UserButtonActionPerformed

    private void ResponsesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponsesButtonActionPerformed
       ChangePanel("Response");
    }//GEN-LAST:event_ResponsesButtonActionPerformed

    private void StatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsButtonActionPerformed
       ChangePanel("Statistics");
    }//GEN-LAST:event_StatisticsButtonActionPerformed

    private void deleteOldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOldButtonActionPerformed
        
        try {
            MainApplication.repository.getRepoStatistics().deleteOldRecords();
            JOptionPane.showMessageDialog(mainFrame, "Success!");
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(mainFrame, "Error!");
        }
        
    }//GEN-LAST:event_deleteOldButtonActionPerformed

    private void updateOldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOldButtonActionPerformed
        try {
            MainApplication.repository.getRepoStatistics().updateOldRecords();
            JOptionPane.showMessageDialog(mainFrame, "Success!");
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(mainFrame, "Error!");
        }
    }//GEN-LAST:event_updateOldButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
     mainFrame.changePanel("LoginRegisterSelection");
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FeedbacksButton;
    private javax.swing.JButton ResponsesButton;
    private javax.swing.JButton StatisticsButton;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JButton UserButton;
    private javax.swing.JButton deleteOldButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton updateOldButton;
    // End of variables declaration//GEN-END:variables
}
