/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FeedbackManagement.GUI;

import FeedbackManagementTables.FeedbackTablePanel;
import FeedbackManagementTables.ResponseTablePanel;
import FeedbackManagementTables.UserTablePanel;
    
/**
 *
 * @author Serhat Korkmaz
 */
public class AdminPanel extends javax.swing.JPanel implements java.beans.Customizer {
    private final MainFrame mainFrame;
    private Object bean;
    private javax.swing.JPanel tablePanel;

    /**
     * Creates new customizer AdminPanel
     */
    public AdminPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    public void ChangePanel(String s){
        TablePanel.removeAll();
        switch (s) {
            case "User":
                tablePanel = new UserTablePanel();
                break;
            case "Feedback":
                tablePanel = new FeedbackTablePanel();
                break;
            case "Response":
                tablePanel = new ResponseTablePanel();
                break;
            default:
                break;
        }
        TablePanel.add(tablePanel);
        TablePanel.validate();
        TablePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePanel = new javax.swing.JPanel();
        UserButton = new javax.swing.JButton();
        FeedbacksButton = new javax.swing.JButton();
        ResponsesButton = new javax.swing.JButton();
        StatisticsButton = new javax.swing.JButton();

        UserButton.setText("Users");
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });

        FeedbacksButton.setText("Feedbacks");
        FeedbacksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbacksButtonActionPerformed(evt);
            }
        });

        ResponsesButton.setText("Responses");
        ResponsesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponsesButtonActionPerformed(evt);
            }
        });

        StatisticsButton.setText("Statistics");
        StatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FeedbacksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResponsesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StatisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 317, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserButton)
                    .addComponent(FeedbacksButton)
                    .addComponent(ResponsesButton)
                    .addComponent(StatisticsButton))
                .addGap(11, 11, 11)
                .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FeedbacksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbacksButtonActionPerformed
        ChangePanel("Feedback");
    }//GEN-LAST:event_FeedbacksButtonActionPerformed

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed
       ChangePanel("User");
    }//GEN-LAST:event_UserButtonActionPerformed

    private void ResponsesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponsesButtonActionPerformed
       ChangePanel("Response");
    }//GEN-LAST:event_ResponsesButtonActionPerformed

    private void StatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatisticsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FeedbacksButton;
    private javax.swing.JButton ResponsesButton;
    private javax.swing.JButton StatisticsButton;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JButton UserButton;
    // End of variables declaration//GEN-END:variables
}
