/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FeedbackManagement.GUI;

import FeedbackManagement.Tables.FeedbackTablePanel;
import FeedbackManagement.Tables.ResponseTablePanel;
import FeedbackManagement.Tables.UserTablePanel;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Serhat Korkmaz
 */
public class CustomerPanel extends javax.swing.JPanel{
    private final MainFrame mainFrame;
    private javax.swing.JPanel tablePanel;

    /**
     * Creates new customizer CustomerPanel
     */
    public CustomerPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }
    
    public void ChangePanel(String s){
        TablePanel.removeAll();
        switch (s) {
            case "Feedback":
                tablePanel = new FeedbackTablePanel();
                break;
            case "Response":
                tablePanel = new ResponseTablePanel();
                break;
            default:
                break;
        }
        TablePanel.add(tablePanel);
        TablePanel.validate();
        TablePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePanel = new javax.swing.JPanel();
        FeedbacksButton = new javax.swing.JButton();
        newFeedbackButton = new javax.swing.JButton();
        responseButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        FeedbacksButton.setText("My Feedbacks");
        FeedbacksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbacksButtonActionPerformed(evt);
            }
        });

        newFeedbackButton.setText("New Feedback");
        newFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFeedbackButtonActionPerformed(evt);
            }
        });

        responseButton.setText("My Responses");
        responseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responseButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FeedbacksButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(responseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newFeedbackButton))
                            .addComponent(logoutButton))
                        .addGap(0, 526, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FeedbacksButton)
                    .addComponent(newFeedbackButton)
                    .addComponent(responseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FeedbacksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbacksButtonActionPerformed
        ChangePanel("Feedback");
    }//GEN-LAST:event_FeedbacksButtonActionPerformed

    private void responseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responseButtonActionPerformed
       ChangePanel("Response");
    }//GEN-LAST:event_responseButtonActionPerformed

    private void newFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFeedbackButtonActionPerformed
        NewFeedbackFrame frame = new NewFeedbackFrame(mainFrame);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);  
    }//GEN-LAST:event_newFeedbackButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainFrame.changePanel("LoginRegisterSelection");
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FeedbacksButton;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton newFeedbackButton;
    private javax.swing.JButton responseButton;
    // End of variables declaration//GEN-END:variables
}
